name: Update

on:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  update_readme:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Download Dependencies
        run: pip install -U requests
      - name: Get Data and Format README
        run: python3 update.py
      - name: Switch from HTTP to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
      - name: Check for changes
        run: git status
      - name: Stage changed files
        run: git add .
      - name: Commit file
        run: git commit -m 'Update Readme'
      - name: Fetch from master
        run: git fetch origin main
      - name: Push code to master
        run: git push origin HEAD:main
