name: Update

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  update_readme:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Download Dependencies
        run: pip install -U requests
      - name: Get Data and Format README
        run: python3 update.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
      - name: Config Github
        run: |
          git config --global user.name "BD103-Action"
          git config --global user.email "dont@stalk.me"
      - name: Check for changes
        run: git status
      - name: Stage changed files
        run: git add .
      - name: Commit file
        run: git commit -m "Build $(date +%D)"
      - name: Fetch from master
        run: git fetch origin main
      - name: Push code to master
        run: git push origin HEAD:main
